backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Blog Yazıları"
    folder: "blog-post"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Başlık", name: "title", widget: "string"}
      - {label: "Yayın Tarihi", name: "date", widget: "datetime"}
      - {label: "Öne Çıkan Görsel", name: "image", widget: "image", required: false}
      - {label: "İçerik", name: "body", widget: "markdown"}
